services:
  mariadb:
    image: mariadb:12.1.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
    ports:
      - $MARIADB_LOCAL_PORT:$MARIADB_DOCKER_PORT
    volumes:
      - mariadbvolume:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MARIADB_ROOT_PASSWORD}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/todolist
    container_name: todolist
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:$MARIADB_DOCKER_PORT/$MARIADB_DATABASE?useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=$MARIADB_USER
      - SPRING_DATASOURCE_PASSWORD=$MARIADB_ROOT_PASSWORD
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  mariadbvolume: